name: Cache Buster

on:
  push:
    branches: [ main ]

jobs:
  bust-cache:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add cache buster version strings
      run: |
        TIMESTAMP=$(date +%s)
        find . -name "*.html" -exec sed -i "s/assets\/style.css/assets\/style.css?v=${TIMESTAMP}/g" {} +
        find . -name "*.html" -exec sed -i "s/assets\/quiz.js/assets\/quiz.js?v=${TIMESTAMP}/g" {} +
        find . -name "*.html" -exec sed -i "s/assets\/results.js/assets\/results.js?v=${TIMESTAMP}/g" {} +

    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Apply cache buster version ${TIMESTAMP}" || echo "No changes to commit"
        git push
